### ISSUE TITLE
Rename `overpassScripts/*` to `overpassScripts/*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [bgrsquared/places#11]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*
Also, it is the most widely used extension on GitHub, see https://github.com/users/FloEdelmann/projects/2/views/2

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@chroth7 Would a pull request be accepted?

**Comment by chroth7** [comment]
thanks @FloEdelmann for offering a PR into that

thing is, I haven't touched this repo for a LONG time now and it is heavily outdated... so I am guessing it could be tricky. Truth be told, I wasn't even aware that the app is still online :-)

so I am not quite sure how to continue here, if we should overhaul the whole thing, if somebody wants to take it over, ...?

happy to discuss!

**Comment by chroth7** [comment]
and I am a bit scared at looking at my 8 year old code 😱

**Comment by FloEdelmann** [comment]
@chroth7 Since this suggestion consists only of renaming some files, the changes should be relatively easy. I created a PR: #12.

**Comment by chroth7** [comment]
@FloEdelmann thanks, you are right, straightforward. As no CI/CD is linked, the impact will be small :-)
