### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by chroth7** [bgrsquared/places#2]
Add permalinks for specific queries?

**Comment by timtomch** [comment]
+1 that would be very useful indeed.

**Comment by chroth7** [comment]
In v2.5.0, I added country and filter settings to the URL.

--> open the tool using bgrsquared.com/places

and the URL will be built reflecting the current country plus mode (advanced or standard)

if advanced, it will include the RegExp
if standard, it will include prefix, suffix, infix and "link" (and/or)

Let me know if you face any problems! (will close in few days if not)
