### ISSUE TITLE
Idea: Click on dot to lock matches

### ISSUE THREAD

**Issue by claudiush** [bgrsquared/places#7]
**Scenario:**
Wanting to dig deeper into the matches for a certain dot and copy the matches. Dot is shown in the middle of the map though, so as soon as mouse cursor moves outside another dot gets selected.

**Idea:**
Click on a dot to lock it, e.g. selection border around the dot and an indicator next to the right hand matches "Matches locked to dot. Click here to release"

**Comment by chroth7** [comment]
(quick note: I haven't forgotten about your valuable input, I was just terribly busy the last weeks - hopefully, soon I will find time!)

**Comment by chroth7** [comment]
Done - source and bgrsquared.com/places updated. Thanks again for the input and sorry for the huge delay!
